"""remove unique on api_keys_project_id

Revision ID: 0c51224b14d4
Revises: c42813a9c4f1
Create Date: 2026-07-08 14:44:10.448222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c51224b14d4'
down_revision: Union[str, None] = 'c42813a9c4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_project_id_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_project_id_key'), 'api_keys', ['project_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
